export const tranList =[
    {
        id:1,
        title:"Laptop",
        date: 2020-3-11,
        category:"IT",
        amount:1000000,
        description:"Good Laptop",
    },
    {
        id:2,
        title:"Iphone 14",
        date: 2020-3-19,
        category:"IT",
        amount:1000,
        description:"Good Phone",
    },
    {
        id:3,
        title:"Laptop",
        date: 2020-3-18,
        category:"IT",
        amount:1000,
        description:"Good Laptop",
    },
    {
        id:4,
        title:"Laptop",
        date: 2020-3-12,
        category:"IT",
        amount:1000,
        description:"Good Laptop",
    },
    {
        id:4,
        title:"Laptop",
        date: 2020-4-11,
        category:"IT",
        amount:1000,
        description:"Good Laptop",
    },
    {
        id:5,
        title:"Laptop",
        date: 2022-3-11,
        category:"IT",
        amount:1000,
        description:"Good Laptop",
    },
    {
        id:6,
        title:"Laptop",
        date: 2021-3-11,
        category:"IT",
        amount:1000,
        description:"Good Laptop",
    },
    {
        id:7,
        title:"Laptop",
        date: 2023-3-11,
        category:"IT",
        amount:1000,
        description:"Good Laptop",
    },
    {
        id:8,
        title:"Laptop",
        date: 2020-7-11,
        category:"IT",
        amount:1000,
        description:"Good Laptop",
    },
    {
        id:9,
        title:"Heinken",
        date: 2020-5-11,
        category:"Beverage",
        amount:1000,
        description:"Good Beverage",
    },
    {
        id:10,
        title:"Rice",
        date: 2021-9-11,
        category:"Food",
        amount:10000,
        description:"Basmat Rice",
    },

]